### ISSUE TITLE
Time support

### ISSUE THREAD

**Issue by jQrgen** [icehaunter/vue3-datepicker#10]
Hey,

Time support: HH:MM would be greatly appreciated.

Maybe I can help?

Thanks

**Comment by icehaunter** [comment]
Hello! Thanks for the attention to the project.

If you want, you can add a time picker, sure. I have no use for it in my current projects, so this will have to be contributed. Restyling the popup slightly shouldn't be a problem, I think.

**Comment by icehaunter** [comment]
Fulfilled currently
