### ISSUE TITLE
NPM Package is behind and does not contain the latest release (0.3.5)

### ISSUE THREAD

**Issue by stuible** [icehaunter/vue3-datepicker#104]
I'm looking to use the new @opened event and it would be great if I could stay on the official npm release.  Any timeline on a fix?

https://www.npmjs.com/package/vue3-datepicker

**Comment by NikolayGogol** [comment]
Agree

**Comment by mydnic** [comment]
@icehaunter could you publish the new version on npm ?

Thanks a lot

**Comment by icehaunter** [comment]
Released the latest, sorry for the dalay.
