### ISSUE TITLE
:start-date not working for week picker

### ISSUE THREAD

**Issue by kevieman** [icehaunter/vue3-datepicker#107]
Hi i'm trying to set a `:start-date` for a week picker like so:
```html
<template>
<Datepicker v-model="dates" :start-date="startDate" placeholder="Select Date" week-picker />
</template>
<script>
    data() {
        dates: [...],
        startDate: new Date(2020, 2),
    }
</script>
```
But this doesnt seem to work.
Start date with normal datepicker works fine.

**Comment by icehaunter** [comment]
Hello, I'm not sure if you're in a correct repository. This component doesn't allow picking multiple dates, doesn't have a `week-picker` prop, or a `start-date` prop. Maybe you're using one of the forks?
