### ISSUE TITLE
When using it as source, it pulls all date-fns locales

### ISSUE THREAD

**Issue by pounard** [icehaunter/vue3-datepicker#25]
I have no explanation yet, I guess it's probably more an issue with date-fns, but I done that (more or less):

```vue
<template>
  <datepicker
    :locale="dateLocale"
  />
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';
import { fr } from 'date-fns/locale';
import Datepicker from '../../../../dist/vue3-datepicker/src/datepicker/Datepicker';

export default defineComponent({
  name: 'foo',
  components: {
    Datepicker,
  },
  data() {
    return {
      dateLocale: fr,
    };
  },
});
</script>
```

And it happens that all date-fns locale end up in my final bundle (even in production mode, after tree shaking). It takes a serious amount of space.

Please note that I'm using a copy of the component source in my own assets folder until #19 is fixed.

**Comment by icehaunter** [comment]
That is strange, that might be a problem with your setup in general. Maybe you're using a bundler that does not tree shake? 

Anyway, #19 is fixed so try that and see if it's better with the component out of `node_modules`.

**Comment by icehaunter** [comment]
Oh, I've also externalized `date-fns/locale` explicitly in rollup config, so you definitely shouldn't get locales in your bundle from the npm package

**Comment by pounard** [comment]
I'll try tomorrow with the new version in node_modules instead of using source directly. By the way, this is unrelated, but I had to patch your source to code to work with my TypeScript config, which seem to be much stricter than yours (but that's not a problem as soon as I'll use the dist version this will not be a problem anymore).

**Comment by pounard** [comment]
OK, so first very good news, the latest release did fix all the bugs I previously experienced ! Thank you very much.

Now, the bad news, but I think it's not your fault, date-fns takes 1.7M in my bundle (including 900K for locales) for a total size of 3M (which means it actually sizes more than an half of my full bundle).

Help appreciated, if you have any idea on how not to import all date-fns locales (I'm asking you, because vue3-datepicker is the only dependent to date-fns in my project, so it's a little bit your fault) :)

**Comment by pounard** [comment]
OK found the solution: if you're interested, you should read: https://github.com/date-fns/date-fns/issues/2188

TL;TD, replace:

```ts
import { fr } from 'date-fns/locale';
```

by:

```ts
import fr from 'date-fns/locale/fr';
```

Because the `date-fns/locale` module acts as a huge index that will force all code to load all locales.

You probably should also adapt your documentation or write a paragraph somewhere, in bold with huge caps, to explain this, believe me your users will thank you!

**Comment by pounard** [comment]
OK there was a bug in date-fns, it has been fixed there https://github.com/date-fns/date-fns/pull/2339 - I guess this issue can be closed now.
