### ISSUE TITLE
inputFormat prop not working

### ISSUE THREAD

**Issue by victorybiz** [icehaunter/vue3-datepicker#28]
`<datepicker v-model="form.date_of_birth" input-format="yyyy-MM-dd" />`
`<datepicker v-model="form.date_of_birth" inputFormat="yyyy-MM-dd" />`

The component is not returning the specified input format, currently, when a date is picked, the `v-model` value returns like `2021-02-26T23:00:00.000Z` and the value of the input like`Sat Feb 27 2021 00:00:00 GMT+0100 (West Africa Standard Time)`

Also, Is there a prop to set a display format for the value input and a different format for value of `v-mode`?

**Comment by victorybiz** [comment]
This issue is not from this plugin but my code, I was using datepicker as a custom input v-bind to `vee-validate` and `vee-validate` auto mutates the value of datepicker.
My workaround was to remove the `v-bind="field"` from the datepicker and then use  two different `v-model` and used computed to update the value of `vee-validate`'s `v-model` when the value of datepicker's `v-model` changes.

**Comment by gul-ahmad** [comment]
can u please explain what was the issue ,I am facing the same issue

**Comment by marcoshmendes** [comment]
@victorybiz  Can you please show some code to understand how you handle this problem within your workaround?

**Comment by olemarius** [comment]
@marcoshmendes here's how: 

```vue
<script lang="ts" setup>
....
const datepickerDate= ref<Date | undefined>();
const date= computed<Date | undefined>(() => datepickerDate.value);
</script>
<template>
...
<Field
    v-slot="{ meta, field, value }"
    v-model="date"
    name="date">
       <Datepicker v-model="datepickerDate" />
</Field>
</template>
```
