### ISSUE TITLE
Seems pack `date-fns` without tree shaking.

### ISSUE THREAD

**Issue by suienzan** [icehaunter/vue3-datepicker#29]
Init a blank vue project. Then import `vue3-datepicker` like this:

```javascript
import picker from "vue3-datepicker";
console.log(picker);
```

Build project will pack `date-fns` without  tree shaking.

**Comment by pounard** [comment]
Please sée #25

**Comment by pounard** [comment]
OK there was a bug in date-fns, it has been fixed there https://github.com/date-fns/date-fns/pull/2339 - I guess this issue can be closed now.

**Comment by suienzan** [comment]
Upgraded `date-fns` to version `2.21.1`. Tree-shaking works as expected now.
