### ISSUE TITLE
format date v-model

### ISSUE THREAD

**Issue by Christophe-miw** [icehaunter/vue3-datepicker#3]
I can't change the date format of the v-model. I've : Thu Nov 05 2020 00:00:00 GMT+0100 (heure normale d’Europe centrale) instead 2020-11-05

**Comment by icehaunter** [comment]
Can you please show how are you using the component?

**Comment by Christophe-miw** [comment]
```<datepicker
    v-model="my_var"
  />```
I had a problem width local #4
I will retest

**Comment by Christophe-miw** [comment]
with local, it's ok
