### ISSUE TITLE
upperLimit / lowerLimit reporting wrong types

### ISSUE THREAD

**Issue by TechSupportJosh** [icehaunter/vue3-datepicker#34]
When using https://github.com/johnsoncodehk/volar, the component reports upperLimit and lowerLimit being of types string | undefined.

```tsc
    upperLimit?: string | undefined;
    lowerLimit?: string | undefined;
```

However, in the documentation as well as the proptype itself, it is a Date | undefined https://github.com/icehaunter/vue3-datepicker/blob/b52fe3d741025f78e52f9eda93d86065c8e41216/src/datepicker/Datepicker.vue#L89-L99

Note that the incorrect type is in vue3-datepicker/dist/Datepicker.vue.d.ts.

**Comment by malthe** [comment]
The generated type information is:
```typescript
    /**
     * Upper limit for available dates for picking
     */
    upperLimit: {
        type: DateConstructor;
        required: false;
    };
```
Where `DateConstructor` takes a string.

**Comment by icehaunter** [comment]
Thanks for the report, sorry for the delayed reaction, will be fixed in the next release
