### ISSUE TITLE
to epoch conversion

### ISSUE THREAD

**Issue by britisharmy** [icehaunter/vue3-datepicker#36]
The date picker gives dates in this format

`Thu Apr 15 2021 00:00:00 GMT+0300 (East Africa Time)`

Could you kindly have a property where one can change the date format and also an epoch format would be the best

For anyone needing datestring generated by the datepicker to epoch

```
      var someDate = new Date(dateString);
      someDate = someDate.getTime();
```

**Comment by icehaunter** [comment]
The date format you're seeing is a standard JS one; this date picker does not return strings. I think this is out of scope for the component and should be easy to do in your code
