### ISSUE TITLE
locale

### ISSUE THREAD

**Issue by Christophe-miw** [icehaunter/vue3-datepicker#4]
when i change :locale="fr" it does not work

**Comment by Vi-system** [comment]
"data-fns" comes by default with vue3-datepicker or you can install it with "npm i data-fns" try:

import { fr } from "date-fns/locale";

in data object:

data() {
    return {
        locale: fr
    }
}

in prop:  " :locale='locale' "

**Comment by Christophe-miw** [comment]
great !
thanks

**Comment by icehaunter** [comment]
Thanks for the response, @Vi-system
