### ISSUE TITLE
Can I open the calendar by clicking on an icon

### ISSUE THREAD

**Issue by nehalfirdausi** [icehaunter/vue3-datepicker#40]
Good afternoon,

I am trying to use vue3-datepicker and my UX requirement is to open the calendar by clicking on an icon and not directly on the input field.

Please advice.

Thank you for your support.

Regards

**Comment by icehaunter** [comment]
Hello, sorry, this project doesn't currently support this functionality. It should be easy to add, however, I'm not adding features at the moment. I'd love a contribution though!

**Comment by icehaunter** [comment]
Actually, this is a duplicate of #6
