### ISSUE TITLE
Empty Datepicker

### ISSUE THREAD

**Issue by nahojj** [icehaunter/vue3-datepicker#43]
I'm trying to initialize the date-picker as empty so all of my users are forced to pick a day but it seems like it doesn't have the support and expects to have a Date object as default?

**Comment by icehaunter** [comment]
Passing the `null` to `v-model` should do the trick. That is not in the docs, however, it is in the local example (`npm run dev` in this repository). If you're having an issue with passing null there - please let me know with more details.
