### ISSUE TITLE
monthHeadingFormat not working

### ISSUE THREAD

**Issue by csikoszoltan** [icehaunter/vue3-datepicker#45]
Hello!
Im trying to set up a different format (yyyy MMMM) for the month view, but nothing is working.
Locale is hu.
My current code is the following:

```javascript
<datepicker
    id="document_date"
    v-model="form.document_date"
    :monthHeadingFormat="'yyyy MMMM'"
    :startingView="'year'"
    :locale="locale"
/>
```
<img width="292" alt="Screenshot 2021-07-05 at 18 17 06" src="https://user-images.githubusercontent.com/44744239/124499201-e9713500-ddbd-11eb-8e33-ad5035d34807.png">

Anyone knows what should I do to change it to year-month format?

Thanks!

**Comment by icehaunter** [comment]
Closed in https://github.com/icehaunter/vue3-datepicker/commit/afa7b0845329e0dd44a379fc7b00322ddf2fb5e2 and released in `v0.3.5`
