### ISSUE TITLE
How to change the language for the days of the week?

### ISSUE THREAD

**Issue by eyey28** [icehaunter/vue3-datepicker#51]
I am confused with the documentation on how to change the language for the days of the week. Could you please give an actual example?

**Comment by spoil349** [comment]
<datepicker
    v-model="date"
    :locale="ru"
/> ...
        
<script>
import Datepicker from 'vue3-datepicker'
import ru from "date-fns/locale/ru"; ...

data() {
    return {
        date: new Date(),
        ru: ru,
    }
  }, ...

**Comment by icehaunter** [comment]
https://icehaunter.github.io/vue3-datepicker/config.html#locale prop is available just for that.

Example for your case:
```vue
<script setup lang="ts">
import { ru } from 'date-fns/locale'
import Datepicker from 'vue3-datepicker'
</script>

<template>
  <Datepicker :locale="ru">
</template>
```
