### ISSUE TITLE
глюк ввода дня при typeable true

### ISSUE THREAD

**Issue by gizmo174** [icehaunter/vue3-datepicker#55]
При вводе даты руками, например, 2021-08-19 вводится 2021-08-019 (календарь переходит на 2021-08-01)
Хочу получить день 19, а этот код
watchEffect (() => (input.value =
props.modelValue && isValid (props.modelValue)
? format (props.modelValue, props.inputFormat, {
locale: props.locale,
})
: ''));
отрабатывает и как только 1 увидел заменил ее на 01

**Comment by icehaunter** [comment]
Fixed in https://github.com/icehaunter/vue3-datepicker/pull/61 (since v0.3.2)
