### ISSUE TITLE
Is it possible to release v0.2.6? Master is ahead

### ISSUE THREAD

**Issue by ianvleeshouwers** [icehaunter/vue3-datepicker#62]
The master branch is up to date but by installing the package but no predicate functionality was found for disabled dates. I was able to use the predicate by running this command: npm i --save vue3-datepicker@icehaunter/vue3-datepicker#master

**Comment by hakobfromlightin** [comment]
> The master branch is up to date but by installing the package but no predicate functionality was found for disabled dates. I was able to use the predicate by running this command: npm i --save vue3-datepicker@icehaunter/vue3-datepicker#master


I have encountered the same problem, although I am having problems importing Datepicker component, can you please share that part, thanks!

**Comment by aon108** [comment]
I am having the same issue. predicate is not being run when pulling from npm. and I get build errors when installing from 
`
npm i --save vue3-datepicker@icehaunter/vue3-datepicker#master
`
please update to 0.2.6 on npm

**Comment by icehaunter** [comment]
Sorry, latest is released now
