### ISSUE TITLE
Example using disabledDates as a function?

### ISSUE THREAD

**Issue by dessery85** [icehaunter/vue3-datepicker#68]
Hi

I am trying to use disabledDates as a function so that I can disable weekends and a few other dates in the datepicker. I have done everything I can think of try and disable it but nothing ever happens. I would like to pass it off to a method in my component to do some processing.

I have tried searching the source code for predicate to see if I could work it out and I can even see a single reference to this parameter.

I am using version 0.2.5.

My apologies if I am being really dumb!

Many thanks
David

**Comment by icehaunter** [comment]
Hello! Sorry for the long reply. First, I would recommend you updated to the latest version. Second, I'm not sure what are you doing incorrectly, but there are examples of this working in `App.vue` local demo. Reach out if it's still relevant!
