### ISSUE TITLE
How to make a global locale config, as well style

### ISSUE THREAD

**Issue by marcoshmendes** [icehaunter/vue3-datepicker#69]
Hello,

I didn't see on docs a way to make a global configuration of locale and style. It's very annoying to add **:locale** every time i use a datepicker on a large app. Is there any way?

**Comment by icehaunter** [comment]
There's explicitly no way to do that, as I like my components isolated. I would suggest you add a higher-order component wrapping this one, which would set the `:locale` prop and CSS variables for styling, and would pass through any other props (attribute fallthrough makes that very easy: https://vuejs.org/guide/components/attrs.html#nested-component-inheritance)
