### ISSUE TITLE
Additional datepicker control shown when clicking icon

### ISSUE THREAD

**Issue by Yannick86** [icehaunter/vue3-datepicker#73]
Hi,

When adding **typeable="false"** the icon on the right of the control is shown, clicking it will prompt an additional datepicker control as shown in the following screenshots. Clicking anywhere else will trigger just one datepicker. I'm guess the icon it's button needs an event prevent default or propagation.

Click in text field:

![image](https://user-images.githubusercontent.com/11870681/142406509-36e09f75-8585-4ea9-94c3-e80d20ec98e7.png)

Click on the icon:

![image](https://user-images.githubusercontent.com/11870681/142406528-e9487f15-9876-4ef4-a340-163343c1df12.png)

**Comment by Yannick86** [comment]
Ok, apparantly we still had type="date" on the field causing Chrome to add the icon and this would show an additional prompt.

**Comment by jagadeshanh** [comment]
@Yannick86 Can you close the issue if it is resolved.
