### ISSUE TITLE
event not working

### ISSUE THREAD

**Issue by YogaHadiN** [icehaunter/vue3-datepicker#74]
I tried to add attribute like @selected or @change in the component. But event handler seems not working at all. How to implement event when date is selected?

**Comment by ahoiroman** [comment]
For me it works with `@update:modelValue`

**Comment by alexlydiate** [comment]
Having the same issue. Need to call an injected method on date selected, so far it @selected does not appear to work.

**Comment by icehaunter** [comment]
`@selected` is not supported at the moment, see #14. @ahoiroman's comment is correct, you can use the event emitted to update the `v-model`
