### ISSUE TITLE
Typeable prop not working with v-model

### ISSUE THREAD

**Issue by pelomedusa** [icehaunter/vue3-datepicker#75]
When using ```v-model``` with the prop `:typeable="true"`, the value is parsed as soon as the format is recognized which results in the following behavior:
![Kazam_screencast_00016](https://user-images.githubusercontent.com/15833842/146386086-47ab8138-e775-47ad-847c-a35c95a2a329.gif)

This may be related to #55 , but unfortunately the issue is in russian, and i do not speak russian :)  

Here is the code sample:
```
<template>
  <label for="" >
    <Datepicker
        v-model="dateValue"
        inputFormat="dd/MM/yyyy"
        :typeable="true"
    />
  </label>
</template>

<script>
import Datepicker from "vue3-datepicker";
import {ref} from "vue";

export default {
  components: {
    Datepicker
  },
  setup(){
    const dateValue = ref(null);
    return {dateValue}
  }
}
</script>
```

**Comment by icehaunter** [comment]
Fixed in https://github.com/icehaunter/vue3-datepicker/pull/61 (since v0.3.2)
