### ISSUE TITLE
it is possible for  cleared input to show the current date.

### ISSUE THREAD

**Issue by actionjacks** [icehaunter/vue3-datepicker#81]
it is possible for cleared input to show the current date.
I want the placeholder text to show up instead of the date
tnx for response

**Comment by icehaunter** [comment]
I'm not sure what you mean. Currently, if you have a placeholder, it'll show up when you clear the input. Otherwise, if you want the "clear" button to set a default value of some kind, just set up a watcher and when the value is set to `null`, set it to a different value
