### ISSUE TITLE
 possible to translate the component to brazilian portuguese ?

### ISSUE THREAD

**Issue by alessandronuunes** [icehaunter/vue3-datepicker#84]
I would like to translate the names of the months and the day of the week to Brazilian standard

**Comment by icehaunter** [comment]
https://icehaunter.github.io/vue3-datepicker/config.html#locale prop is available just for that.

Example for your case:
```vue
<script setup lang="ts">
import { ptBR } from 'date-fns/locale'
import Datepicker from 'vue3-datepicker'
</script>

<template>
  <Datepicker :locale="ptBR">
</template>
```
